### ISSUE TITLE
Upload to Store

### ISSUE THREAD

**Issue by haylinmoore** [iwotastic/furball#1]
Will you ever upload this to the chrome store? If not I will be willing to upload this, as I LOVE furball

**Comment by iwotastic** [comment]
Trying to. 😝 Got to get the $5 paid though. ☹️

**Comment by iwotastic** [comment]
I've done it. It is available [here](https://chrome.google.com/webstore/detail/furball/okeennfbdbebolgjgokolfdgnjkaikla?hl=en-US).
