### ISSUE TITLE
background js is broken

### ISSUE THREAD

**Issue by andybrwr** [iwotastic/furball#2]
apparently there's an unexpected = on line 13 somewhere, idk how that arrow works but i think it is the second one

**Comment by ALinuxLover** [comment]
now:

Error in event handler for storage.onChanged: TypeError: Cannot read property 'newValue' of undefined
    at chrome.storage.onChanged.addListener (chrome-extension://dpknbeoglcnikfflopfjjicoachhbmfd/background.js:54:26)
