### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by haylinmoore** [iwotastic/furball#5]
https://scratch.mit.edu/discuss/topic/273264/?page=1#post-2773939

**Comment by CosmicWebServices** [comment]
Already added not on app store yet
-IcyCoder

**Comment by iwotastic** [comment]
Once I'm back from vacation, I will upload Furball 1.4 with this addition included. I will close this once it has been uploaded.

**Comment by iwotastic** [comment]
Closing because of Web Store release.
